<script type="text/javascript">
	function fill(i, n) {
			i = i + "";
					l = i.length;
							if (n > l) {
										l = n - l;
													for (k = 0; k < l; k++) {
																	i = "0" + i
																				}
																						}
																								return i
																									}
																										function gid_iframe(id) {
																												var doc;
																														if (document.all) {
																																	doc = document.frames[id].document
																																			} else {
																																						doc = gid(id).contentDocument
																																								}
																																										return doc
																																											}
																																												var mycb = function() {
																																														var con = document.getElementById("content");
																																																var box2 = document.createElement("div");
																																																		box2.setAttribute("id", "mybox2");
																																																				con.parentNode.insertBefore(box2, con);
																																																						var html = '<table>';
																																																								html += '<tr><td style="width: 121px; text-align: right;"><label>�� ��</label>��</td><td><input type="text" id="name2" name="name2" value="" /><br />׼ȷ������������ǰ�����֣����������ɼ��Ĺؼ�һ��</td></tr>';
																																																										html += '<tr><td style="width: 121px; text-align: right;"><label>����ѡ��</label>��</td><td><select name="sroom" id="sroom"><option value="0">��ѡ�񿼳�...</option>';
																																																												for ( var i = 1; i <= 700; i++) {
																																																															html += "<option value='"+i+"'>" + i + "</option>"
																																																																	}
																																																																			;
																																																																					html += '</select>����<select name="eroom" id="eroom"><option value="0">��ѡ�񿼳�...</option>';
																																																																							for ( var i = 1; i <= 700; i++) {
																																																																										html += "<option value='"+i+"'>" + i + "</option>"
																																																																												}
																																																																														;
																																																																																html += '</select><br /><span class="input-tip">����ѡĬ�ϲ�ѯ��׼����ͬһ�����ģ�ע����ѡ����Χ�����ɼ�����ʱ�䡿</span></td></tr><tr><td style="width: 121px; text-align: right;"><label>��λѡ��</label>��</td><td>     <select name="pos" id="pos"><option value="0">=��λ��==</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option><option value="9">9</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option></select><br /><span class="input-tip">�����ǵ���λ�ţ������ٶȽ��ӿ�N����</span></td></tr><tr><td style="text-align: right;"><label>����Χ������һ��׼����</label>��</td><td><input id="code" name="code" size="30" /><button id="query" onclick="query();">��ѯ</button><br /><span class="input-tip">��ѯ����ֻ��ʾ����</span></td></tr> ';
																																																																																		��" id="export" />   </p><br /><div id="loading2">�����������ĳɼ�......<img src="images/wait.gif" /> <span style="font-size:120%;color:red;font-weight:bold;" id="process">0%</span></div><div id="report"></div><div id="report_init" style="display:none;"><table id="rtbl" width="700" cellpadding=0 cellspacing=0><tr><th width="20%">׼��֤</th><th width="20%">ѧУ</th><th width="10%">����</th><th width="8%">����</th><th width="8%">�Ķ�</th><th width="8%">�ۺ�</th><th width="8%">д��</th><th width="20%"><span style="color:red;">�ܷ�</span></th></tr></table></div></div>';
																																																																																				html += '<iframe id="searchframe2" name="searchframe2" src="about:blank" style="display: none;"  onload="javascript:ifrload2();"></iframe>';
																																																																																						document.getElementById("mybox2").innerHTML = html;
																																																																																								document.getElementById("searchform").setAttribute("target",
																																																																																												"searchframe2")
																																																																																													};
																																																																																														var hasFind = false, pos = 0, sroom = 0, eroom = 0, c = 0, rc = 0, code = '';
																																																																																															function query() {
																																																																																																	hasFind = false;
																																																																																																			pos = document.getElementById("pos").value;
																																																																																																					sroom = parseInt(document.getElementById("sroom").value);
																																																																																																							eroom = parseInt(document.getElementById("eroom").value);
																																																																																																									n = document.getElementById("name2");
																																																																																																											if (n.value == '' || n.value == name_blank) {
																																																																																																														n.value = '';
																																																																																																																	n.focus();
																																																																																																																				alert('����������������ǰ�����֣�');
																																																																																																																							return false
																																																																																																																									}
																																																																																																																											if (sroom > eroom || sroom == 0 || eroom == 0) {
																																																																																																																														alert("����ȷѡ�񿼳���Χ��");
																																																																																																																																	return false
																																																																																																																																			}
																																																																																																																																					min = 1;
																																																																																																																																							code = document.getElementById("code").value;
																																																																																																																																									if (code == '') {
																																																																																																																																												alert("������׼��֤���룡");
																																																																																																																																															return false
																																																																																																																																																	}
																																																																																																																																																			if (code.length < 10) {
																																																																																																																																																						alert("����������׼��֤������ǰ10λ���ɲο��ײ�����׼��֤��˵��");
																																																																																																																																																									document.getElementById("code").focus();
																																																																																																																																																												return false
																																																																																																																																																														}
																																																																																																																																																																if (sroom == 0 && eroom == 0) {
																																																																																																																																																																			s = code.substr(0, 13)
																																																																																																																																																																					} else {
																																																																																																																																																																								s = code.substr(0, 10) + fill(sroom, 3)
																																																																																																																																																																										}
																																																																																																																																																																												c = pos > 0 ? pos : 1;
																																																																																																																																																																														rc = sroom;
																																																																																																																																																																																last = s + c;
																																																																																																																																																																																		document.getElementById("report").innerHTML = (document
																																																																																																																																																																																						.getElementById("report_init").innerHTML);
																																																																																																																																																																																								document.getElementById("ret").style.display = "block";
																																																																																																																																																																																										document.getElementById("codestr").innerHTML = (code);
																																																																																																																																																																																												document.getElementById("loading2").innerHTML = ('�����������ĳɼ�......<img src="images/wait.gif" /> <span style="font-size:120%;color:red;font-weight:bold;" id="process"></span>');
																																																																																																																																																																																														document.getElementById("loading2").style.display = "block";
																																																																																																																																																																																																document.getElementById("code").setAttribute("disabled", true);
																																																																																																																																																																																																		document.getElementById("sroom").setAttribute("disabled", true);
																																																																																																																																																																																																				document.getElementById("eroom").setAttribute("disabled", true);
																																																																																																																																																																																																						document.getElementById("name2").setAttribute("disabled", true);
																																																																																																																																																																																																								p(code)
																																																																																																																																																																																																									}
																																																																																																																																																																																																										function p(code) {
																																																																																																																																																																																																												if (hasFind)
																																																																																																																																																																																																															return;
																																																																																																																																																																																																																	if (rc > eroom) {
																																																																																																																																																																																																																				c = 0;
																																																																																																																																																																																																																							document.getElementById("query").setAttribute("disabled", false);
																																																																																																																																																																																																																										document.getElementById("code").setAttribute("disabled", false);
																																																																																																																																																																																																																													document.getElementById("sroom").setAttribute("disabled", false);
																																																																																																																																																																																																																																document.getElementById("eroom").setAttribute("disabled", false);
																																																																																																																																																																																																																																			document.getElementById("name2").setAttribute("disabled", false);
																																																																																																																																																																																																																																						document.getElementById("loading2").innerHTML = ("��ѡ������Χû�з����㡣");
																																																																																																																																																																																																																																									return
																																																																																																																																																																																																																																											}
																																																																																																																																																																																																																																													s = code.substr(0, 10) + fill(rc, 3) + fill(c, 2);
																																																																																																																																																																																																																																															name = document.getElementById("name2").value;
																																																																																																																																																																																																																																																	document.getElementById("name").value = (name);
																																																																																																																																																																																																																																																			document.getElementById("id").value = (s);
																																																																																																																																																																																																																																																					document.searchform.submit()
																																																																																																																																																																																																																																																						}
																																																																																																																																																																																																																																																							function ifrload2() {
																																																																																																																																																																																																																																																									var doc = gid_iframe("searchframe2");
																																																																																																																																																																																																																																																											score = doc.body.innerHTML;
																																																																																																																																																																																																																																																													score = score.replace(/<.*?>/g, "");
																																																																																																																																																																																																																																																															score = score.trim();
																																																																																																																																																																																																																																																																	if (score != "" && score.length > 7) {
																																																																																																																																																																																																																																																																				document.getElementById("process").innerHTML = ('100%');
																																																																																																																																																																																																																																																																							document.getElementById("loading2").innerHTML = ('<span style="color:red; font-size:18px;">��ϲ���Ѿ��ҵ����Ŀ��Գɼ���</span>');
																																																																																																																																																																																																																																																																										document.getElementById("query").setAttribute("disabled", false);
																																																																																																																																																																																																																																																																													document.getElementById("code").setAttribute("disabled", false);
																																																																																																																																																																																																																																																																																document.getElementById("sroom").setAttribute("disabled", false);
																																																																																																																																																																																																																																																																																			document.getElementById("eroom").setAttribute("disabled", false);
																																																																																																																																																																																																																																																																																						document.getElementById("name2").setAttribute("disabled", false);
																																																																																																																																																																																																																																																																																									tmp = score.split(",");
																																																																																																																																																																																																																																																																																												var ss = '';
																																																																																																																																																																																																																																																																																															ss += '<td align="center">' + s + '</td>';
																																																																																																																																																																																																																																																																																																		ss += '<td align="center">' + (tmp[6] ? tmp[6] : '--') + '</td>';
																																																																																																																																																																																																																																																																																																					ss += '<td align="center">' + (tmp[7] ? tmp[7] : '--') + '</td>';
																																																																																																																																																																																																																																																																																																								ss += '<td align="center">' + (tmp[1] ? tmp[1] : '--') + '</td>';
																																																																																																																																																																																																																																																																																																											ss += '<td align="center">' + (tmp[2] ? tmp[2] : '--') + '</td>';
																																																																																																																																																																																																																																																																																																														ss += '<td align="center">' + (tmp[3] ? tmp[3] : '--') + '</td>';
																																																																																																																																																																																																																																																																																																																	ss += '<td align="center">' + (tmp[4] ? tmp[4] : '--') + '</td>';
																																																																																																																																																																																																																																																																																																																				ss += '<td align="center">' + (tmp[5] ? tmp[5] : '--') + '</td>';
																																																																																																																																																																																																																																																																																																																							ss += '</tr>';
																																																																																																																																																																																																																																																																																																																										document.getElementById("rtbl").innerHTML += (ss);
																																																																																																																																																																																																																																																																																																																													rc = c = 1
																																																																																																																																																																																																																																																																																																																															} else {
																																																																																																																																																																																																																																																																																																																																		if (score != "") {
																																																																																																																																																																																																																																																																																																																																						document.getElementById("process").innerHTML = (' ��ǰ' + rc
																																																																																																																																																																																																																																																																																																																																												+ '����' + c + '��λ');
																																																																																																																																																																																																																																																																																																																																																if (pos > 0) {
																																																																																																																																																																																																																																																																																																																																																					c = pos;
																																																																																																																																																																																																																																																																																																																																																										rc++
																																																																																																																																																																																																																																																																																																																																																														} else {
																																																																																																																																																																																																																																																																																																																																																																			if (c >= 30) {
																																																																																																																																																																																																																																																																																																																																																																									c = 1;
																																																																																																																																																																																																																																																																																																																																																																															rc++
																																																																																																																																																																																																																																																																																																																																																																																				} else {
																																																																																																																																																																																																																																																																																																																																																																																										c++
																																																																																																																																																																																																																																																																																																																																																																																															}
																																																																																																																																																																																																																																																																																																																																																																																																			}
																																																																																																																																																																																																																																																																																																																																																																																																							setTimeout("p(code)", 800)
																																																																																																																																																																																																																																																																																																																																																																																																										}
																																																																																																																																																																																																																																																																																																																																																																																																												}
																																																																																																																																																																																																																																																																																																																																																																																																													}
																																																																																																																																																																																																																																																																																																																																																																																																														mycb();
																																																																																																																																																																																																																																																																																																																																																																																																														</script>
																																																																																																																																																																																																																																																																																																																																																																																																														html += '</table>';
																																																																																				html += '<style>table{line-height:24px}</style>';
																																																																																						html += '<div style="display:none;" id="ret"><h2>��ѯ����</h2><p style="">������ʹ��<span style="color:orange;font-family:verdana;" id="codestr"></span>����׼��֤�Ų�ѯ <!--|||<input type="button" onclick="exportit();" value="����ΪExcel
